import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ReactNode} from "react";
import MainContainer from "@/components/Containers/MainContainer";
import MainProvider from "@/providers/MainProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{minHeight: "100vh"}}>
      <MainProvider>
        <MainContainer>{children}</MainContainer>
      </MainProvider>
      </body>
    </html>
  )
}
